### ISSUE TITLE
FAQ page

### ISSUE THREAD

**Issue by szewczykmira** [scoiatael/zosia16-site#17]
We should make FAQ page. I hope people would read it :)

**Comment by szewczykmira** [comment]
@scoiatael what do you think about defining QA as model? Every object contains question and answear for it. Also it would be easy to define new questions (you don't need to change html)

**Comment by szewczykmira** [comment]
@scoiatael are you alive? :)

**Comment by scoiatael** [comment]
Providing we add proper caching then sure ;)

**Comment by szewczykmira** [comment]
- [x] cache

- [x] add

- [x] edit

- [x] display for users

- [x] display for admin

- [x] delete

- [x] tests
