### ISSUE TITLE
Errors in tests

### ISSUE THREAD

**Issue by szewczykmira** [scoiatael/zosia16-site#55]
There are some errors in **rooms** module when there are started with `./manage.py test`.
It should be fixed. Also - we need to make sure that tests made with `make` and `./manage.py test` gives the same output.

**Comment by scoiatael** [comment]
Cannot reproduce: 
```
(env) l@Arch-Lenovo ~/D/o/zosia16-site> ./manage.py test
Creating test database for alias 'default'...
........................................................................................................
----------------------------------------------------------------------
Ran 104 tests in 8.092s

OK
Destroying test database for alias 'default'...
(env) l@Arch-Lenovo ~/D/o/zosia16-site> git log -1
commit caea8b6a81d37f3f6f67e4eed3ec743af81a2615
Merge: 8371d6e ced334b
Author: Mira Szewczyk <szewczyk.mira@gmail.com>
Date:   Sun Jan 15 15:31:04 2017 +0100

    Merge pull request #52 from scoiatael/links

    Add links
```

**Comment by scoiatael** [comment]
Connected to cache settings in tests: TODO: move test cache settings to tests themselves.

**Comment by scoiatael** [comment]
Turns out Django does not cache _per user_ by default. Fix: re-order headers to apply `vary on cookie` _after_ `cache` - this forces django to cache per-user ;)
